name: "production"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  main:
    defaults:
      run:
        shell: "bash"
        working-directory: "${{ matrix.directory }}"
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    environment:
      name: "production"
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        directory:
          - "model"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.8"
      - uses: "hashicorp/setup-terraform@v2"
      - run: |
          pip install \
          -r ./src/requirements.txt \
          -t ./src/python \
          --no-cache-dir \
          --no-color \
          --no-user \
          --verbose
      - run: |
          terraform init \
          -input=false \
          -no-color \
          -reconfigure
      - run: |
          terraform apply \
          -auto-approve \
          -input=false \
          -no-color
