name: "pull_request"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  main:
    defaults:
      run:
        shell: "bash"
    environment:
      name: "development"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        directory:
          - "model"
          - "mysql"
    steps:
      - uses: actions/checkout@v3
      - uses: "lindsaygelle/AWSAnimalCrossingWorkflows/.github/actions/terraform@main"
        with:
          terraform_check: true
          terraform_init: true
          terraform_fmt: true
          terraform_plan: true
          working_directory: "${{ matrix.directory }}"
