name: "test"

on:
  workflow_dispatch:

jobs:
  main:
    defaults:
      run:
        shell: "bash"
    environment:
      name: "production"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    permissions:
      contents: "write"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        directory:
          - "model"
          - "mysql"
    steps:
      - uses: actions/checkout@v3
      - name: pip
        uses: "lindsaygelle/AWSAnimalCrossingWorkflows/.github/actions/pip@dev"
        working-directory: ${{ matrix.directory }}
